version: "2"
services:
  theme-park-ride-gradle:
    image: registry.gitlab.com/jhiberne/theme-park-ride-gradle:latest
    container_name: theme-park-ride-gradle
    mem_limit: 512M
    ports:
      - 5000:5000
  mysql:
    image: mysql:5.7
    container_name: mysql
    mem_limit: 512M
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: themepark
    ports:
      - 3306:3306
