version: "2"
services:
  theme-park-ride:
    image: farloche/tpr:0.1.0
    container_name: theme-park-ride
    mem_limit: 512M
    restart: on-failure
    depends_on: 
      - db
    ports:
      - 5000:5000
  db:
    image: mysql:8.0
    container_name: mysql
    mem_limit: 512M
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: themepark
      MYSQL_USER: username
      MYSQL_PASSWORD: password
