apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.name }}-deployment"
  labels: 
     app: "{{ .Chart.name }}"
spec:
  replicas: {{ .Values.replicas.count }}
  selector:
    matchLabels:
       app: "{{ .Chart.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.name }}"
    spec:
      containers:
        - name: "{{ .Chart.name }}"
          image: "{{ .Values.repository }}:{{ .Values.tag}} | default .Chart.appVersion }}"
          env:
            - name: DB_URL
              value: "${{ .Values.db_url }}"
            - name: DB_USERNAME
              value: "${{ .Values.db_username }}"
            - name: DB_PASSWORD
              value: "{{ .Values.db_password }}"
          ports:
            - containerPort: 5000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress_name }}
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
             service:
              name: {{.Values.clusterip }}
              port:
                number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: {{.Values.clusterip }}
spec:
  selector:
    app: {{ .Chart.name }}
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
