ingressClass:
  enabled: true
  isDefaultClass: true
  fallbackApiVersion: v1
ingressRoute:
  dashboard:
    enabled: false

service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10

ports:
  web:
    expose: false
  websecure:
    nodePort: 32443