name: Docker run test DB
run-name: ${{ github.actor }} / Docker run test DB 🚀

on: 
  workflow_call:

jobs:
  docker-run-test-db:
    runs-on: ubuntu-latest
    env:
      BUILD_DB_HOST: localhost
      BUILD_DB_NAME: themepark
      BUILD_DB_USERNAME: 'username'
      BUILD_DB_PASSWORD: 'password'
    steps:
      - name: Docker run test DB
        run: |
          export MYSQL_DATABASE=$BUILD_DB_NAME
          export MYSQL_USER=$BUILD_DB_USERNAME
          export MYSQL_PASSWORD=$BUILD_DB_PASSWORD
          docker run -d --name db -e MYSQL_RANDOM_ROOT_PASSWORD=yes  -e MYSQL_DATABASE -e MYSQL_USER -e MYSQL_PASSWORD -p 3306:3306 mysql:8.0
