name: Build docker image

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Release Version
        run: |
          echo "IMAGE_TAG=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "IMAGE_NAME=themeparkride" >> $GITHUB_ENV

      - name: Build Image
        run: |
          docker build -t DOCKERHUB_USERNAME/IMAGE_NAME:${{ env.IMAGE_TAG }} -f Dockerfile .
          docker build -t DOCKERHUB_USERNAME/IMAGE_NAME:latest -f Dockerfile .

      - name: Push Image
        run: |
          docker push DOCKERHUB_USERNAME/IMAGE_NAME:${{ env.IMAGE_TAG }}
          docker push DOCKERHUB_USERNAME/IMAGE_NAME:latest
