name: Deploy
run-name: ${{ github.actor }} is deploying  ${{ github.repository }} ${{ github.ref }} 🚀
on:
  push:
    branches:
    - cja-deploy
    
# on:
#  workflow_dispatch:
#    inputs:
#      environment:
#        description: 'Environnement de destination'
#        required: true
#        default: 'dev'
#        type: choice
#        options:
#        - dev
#        - prod
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout gui-helm-chart
        uses: actions/checkout@v4
        with:
          ref: refs/heads/gui-helm-chart
      - name: check checkout
        run: |
          cat helm-chart/*
      - name: setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: eu-west-3
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: setup kubeconfig
        run: |
          aws eks update-kubeconfig --region eu-west-3 --name tmptpr
          kubectl get all
#      - name: deploy hello world on dev
#        run: |
#          helm repo add examples https://helm.github.io/examples
#          helm install -n dev  hello-world examples/hello-world --set service.port=3380
