name: Deploy on dev
run-name: ${{ github.actor }} / Deploy on dev 🐱

on:
  workflow_run:
    workflows: [Build docker image]
    types:
      - completed
    branches:
      - dev

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: setup kubeconfig
        run: |
          export AWS_REGION=${{ vars.AWS_REGION }}
          aws eks update-kubeconfig --region $AWS_REGION --name tmptpr
      - name: deploy on dev
        run: |
          export HOST_DEV=${{ vars.HOST_DEV }}
          export DB_HOST="${{ vars.DB_HOST }}"
          export DB_NAME_DEV="${{ vars.DB_NAME_DEV }}"
          export DB_URL=`echo jdbc:mysql://$DB_HOST:3306/$DB_NAME_DEV`
          export DB_USERNAME="${{ vars.DB_USERNAME_DEV }}"
          export DB_PASSWORD="${{ secrets.DB_USER_PW_DEV }}"
          helm template tpr -n dev --values ./helm-chart/values.yml --set host=$HOST_DEV --set db_url=$DB_URL  --set db_password=$DB_PASSWORD --set db_username=$DB_USERNAME ./helm-chart
          helm upgrade --install tpr -n dev --values ./helm-chart/values.yml --set host=$HOST_DEV --set db_url=$DB_URL  --set db_password=$DB_PASSWORD --set db_username=$DB_USERNAME ./helm-chart
  on-build-docker-image-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Build docker image failed. Can't deploy on dev"
          exit 1
