name: Deploy
run-name: ${{ github.actor }} is deploying  ${{ github.repository }} ${{ github.ref }} 🚀
on:
  push:
    branches:
    - cja-deploy
    
# on:
#  workflow_dispatch:
#    inputs:
#      environment:
#        description: 'Environnement de destination'
#        required: true
#        default: 'dev'
#        type: choice
#        options:
#        - dev
#        - prod
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout gui-helm-chart
        uses: actions/checkout@v4
        with:
          ref: refs/heads/gui-helm-chart          
      - name: setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: eu-west-3
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: setup kubeconfig
        run: |
          aws eks update-kubeconfig --region eu-west-3 --name tmptpr
      - name: deploy on dev
        run: |
          export
          export DB_URL="jdbc:mysql://tpr-db.cx0riniaqwhm.eu-west-3.rds.amazonaws.com:3306/themepark_dev"
#          export DB_USERNAME=tpr_dev_db_user
#          export DB_PASSWORD=${{ secrets.DB_USER_PW_DEV }}
#          export
#          cat ./helm-chart/values.yml
#          helm template tpr -n dev --values ./helm-chart/values.yml --set db_url=$DB_URL  --set db_password=$DB_PASSWORD --set db_username=$DB_USERNAME ./helm-chart
