name: Deploy on dev
run-name: ${{ github.actor }} / Deploy on dev 🐱
on:
  workflow_run:
    workflows: ["build-image"]
    types: [completed]
    branches: 
      - dev
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout gui-helm-chart
        uses: actions/checkout@v4
        with:
          ref: refs/heads/dev         
      - name: setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: eu-west-3
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: setup kubeconfig
        run: |
          aws eks update-kubeconfig --region eu-west-3 --name tmptpr
      - name: deploy on dev
        run: |
          export DB_HOST="${{ vars.DB_HOST }}"
          export DB_NAME_DEV="${{ vars.DB_NAME_DEV }}"
          export DB_URL=`echo jdbc:mysql://$DB_HOST:3306/$DB_NAME_DEV`
          echo $DB_URL
          export DB_USERNAME="${{ vars.DB_USERNAME_DEV }}"
          export DB_PASSWORD="${{ secrets.DB_USER_PW_DEV }}"
          cat ./helm-chart/values.yml
          helm upgrade --install tpr -n dev --values ./helm-chart/values.yml --set host=dev.tpr.cloudns.org --set db_url=$DB_URL  --set db_password=$DB_PASSWORD --set db_username=$DB_USERNAME ./helm-chart
