name: Deploy on prod
run-name: ${{ github.actor }} / Deploy on prod 🎢

on:
  workflow_run:
    workflows: [Build docker image]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: setup kubeconfig
        run: |
          export AWS_REGION=${{ vars.AWS_REGION }}
          aws eks update-kubeconfig --region $AWS_REGION --name tmptpr
      - name: deploy on prod
        run: |
          export HOST_PROD=${{ vars.HOST_PROD }}
          export DB_HOST="${{ vars.DB_HOST }}"
          export DB_NAME_PROD="${{ vars.DB_NAME_PROD }}"
          export DB_URL=`echo jdbc:mysql://$DB_HOST:3306/$DB_NAME_PROD`
          export DB_USERNAME="${{ vars.DB_USERNAME_PROD }}"
          export DB_PASSWORD="${{ secrets.DB_USER_PW_PROD }}"
          helm upgrade --install tpr -n prod --values ./helm-chart/values.yml --set host=$HOST_PROD --set db_url=$DB_URL  --set db_password=$DB_PASSWORD --set db_username=$DB_USERNAME ./helm-chart
  on-build-docker-image-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "Build docker image failed. Can't deploy on prod"
          exit 1