name: reusable docker build and docker hub push 
run-name: run by ${{ github.actor }}

on:
  workflow_call:
      inputs:
        image_tag:
          required: true
          type: string

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build image
        run: |
          docker build -t ${{ vars.DOCKERHUB_HOST }}/themeparkride:${{ inputs.image_tag }} -f Dockerfile .
          docker build -t ${{ vars.DOCKERHUB_HOST }}/themeparkride:latest -f Dockerfile .
      - name: push image
        run: |
          docker push ${{ vars.DOCKERHUB_HOST }}/themeparkride:${{ inputs.image_tag }}
          docker push ${{ vars.DOCKERHUB_HOST }}/themeparkride:latest
